//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FINAL
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "Id as \'Id\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "СерияП as \'Серия паспорта\'",
            "НомерП as \'Номер паспорта\'",
            "Должности as \'Должности\'",
            "Должности.Название as \'Должность\'",
            "Отделы as \'Отделы\'",
            "Отделы.Наименование as \'Отдел\'",
            "Организации as \'Организации\'",
            "Организации.Название as \'Организация\'"}, Hidden=new string[] {
            "Должности.Название",
            "Отделы.Наименование",
            "Организации.Название"})]
    [MasterViewDefineAttribute("СотрудникиE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("СотрудникиE", "Отделы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("СотрудникиE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("СотрудникиL", new string[] {
            "Id as \'Id\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "СерияП as \'Серия паспорта\'",
            "НомерП as \'Номер паспорта\'",
            "Должности.Название as \'Должность\'",
            "Отделы.Наименование as \'Отдел\'",
            "Организации.Название as \'Организация\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private int fId;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private string fСерияП;
        
        private string fНомерП;
        
        private IIS.FINAL.Должности fДолжности;
        
        private IIS.FINAL.Отделы fОтделы;
        
        private IIS.FINAL.Организации fОрганизации;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// Id.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Id CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Id CustomAttributes)
        public virtual int Id
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Id Get start)

                // *** End programmer edit section *** (Сотрудники.Id Get start)
                int result = this.fId;
                // *** Start programmer edit section *** (Сотрудники.Id Get end)

                // *** End programmer edit section *** (Сотрудники.Id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Id Set start)

                // *** End programmer edit section *** (Сотрудники.Id Set start)
                this.fId = value;
                // *** Start programmer edit section *** (Сотрудники.Id Set end)

                // *** End programmer edit section *** (Сотрудники.Id Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Имя CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Имя Get start)

                // *** End programmer edit section *** (Сотрудники.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Сотрудники.Имя Get end)

                // *** End programmer edit section *** (Сотрудники.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Имя Set start)

                // *** End programmer edit section *** (Сотрудники.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Сотрудники.Имя Set end)

                // *** End programmer edit section *** (Сотрудники.Имя Set end)
            }
        }
        
        /// <summary>
        /// НомерП.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.НомерП CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.НомерП CustomAttributes)
        [StrLen(255)]
        public virtual string НомерП
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.НомерП Get start)

                // *** End programmer edit section *** (Сотрудники.НомерП Get start)
                string result = this.fНомерП;
                // *** Start programmer edit section *** (Сотрудники.НомерП Get end)

                // *** End programmer edit section *** (Сотрудники.НомерП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.НомерП Set start)

                // *** End programmer edit section *** (Сотрудники.НомерП Set start)
                this.fНомерП = value;
                // *** Start programmer edit section *** (Сотрудники.НомерП Set end)

                // *** End programmer edit section *** (Сотрудники.НомерП Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Отчество CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Отчество Get start)

                // *** End programmer edit section *** (Сотрудники.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Сотрудники.Отчество Get end)

                // *** End programmer edit section *** (Сотрудники.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Отчество Set start)

                // *** End programmer edit section *** (Сотрудники.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Сотрудники.Отчество Set end)

                // *** End programmer edit section *** (Сотрудники.Отчество Set end)
            }
        }
        
        /// <summary>
        /// СерияП.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.СерияП CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.СерияП CustomAttributes)
        [StrLen(255)]
        public virtual string СерияП
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.СерияП Get start)

                // *** End programmer edit section *** (Сотрудники.СерияП Get start)
                string result = this.fСерияП;
                // *** Start programmer edit section *** (Сотрудники.СерияП Get end)

                // *** End programmer edit section *** (Сотрудники.СерияП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.СерияП Set start)

                // *** End programmer edit section *** (Сотрудники.СерияП Set start)
                this.fСерияП = value;
                // *** Start programmer edit section *** (Сотрудники.СерияП Set end)

                // *** End programmer edit section *** (Сотрудники.СерияП Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Фамилия Get start)

                // *** End programmer edit section *** (Сотрудники.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Сотрудники.Фамилия Get end)

                // *** End programmer edit section *** (Сотрудники.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Фамилия Set start)

                // *** End programmer edit section *** (Сотрудники.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Сотрудники.Фамилия Set end)

                // *** End programmer edit section *** (Сотрудники.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должности CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.FINAL.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Get start)

                // *** End programmer edit section *** (Сотрудники.Должности Get start)
                IIS.FINAL.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Сотрудники.Должности Get end)

                // *** End programmer edit section *** (Сотрудники.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Set start)

                // *** End programmer edit section *** (Сотрудники.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Сотрудники.Должности Set end)

                // *** End programmer edit section *** (Сотрудники.Должности Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Организации CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Организации CustomAttributes)
        [PropertyStorage(new string[] {
                "Организации"})]
        [NotNull()]
        public virtual IIS.FINAL.Организации Организации
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Организации Get start)

                // *** End programmer edit section *** (Сотрудники.Организации Get start)
                IIS.FINAL.Организации result = this.fОрганизации;
                // *** Start programmer edit section *** (Сотрудники.Организации Get end)

                // *** End programmer edit section *** (Сотрудники.Организации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Организации Set start)

                // *** End programmer edit section *** (Сотрудники.Организации Set start)
                this.fОрганизации = value;
                // *** Start programmer edit section *** (Сотрудники.Организации Set end)

                // *** End programmer edit section *** (Сотрудники.Организации Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Отделы CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Отделы CustomAttributes)
        [PropertyStorage(new string[] {
                "Отделы"})]
        [NotNull()]
        public virtual IIS.FINAL.Отделы Отделы
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Отделы Get start)

                // *** End programmer edit section *** (Сотрудники.Отделы Get start)
                IIS.FINAL.Отделы result = this.fОтделы;
                // *** Start programmer edit section *** (Сотрудники.Отделы Get end)

                // *** End programmer edit section *** (Сотрудники.Отделы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Отделы Set start)

                // *** End programmer edit section *** (Сотрудники.Отделы Set start)
                this.fОтделы = value;
                // *** Start programmer edit section *** (Сотрудники.Отделы Set end)

                // *** End programmer edit section *** (Сотрудники.Отделы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.FINAL.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.FINAL.Сотрудники));
                }
            }
        }
    }
}
